### ISSUE TITLE
I am integrating sclaoid and AutobahnAndroid but getting error

### ISSUE THREAD

**Issue by amitprasadom** [pocorall/scaloid#114] opened 2015-01-23 05:53 UTC
[info] Loading global plugins from /home/amit/.sbt/0.13/plugins
[info] Loading project definition from /home/amit/Downloads/hello-scaloid-sbt-master/project
[info] Set current project to hello-scaloid-sbt (in build file:/home/amit/Downloads/hello-scaloid-sbt-master/)
[info] Updating {file:/home/amit/Downloads/hello-scaloid-sbt-master/}hello-scaloid-sbt-master...
[info] Resolving jline#jline;2.12 ...
[info] Done updating.
[info] Processing resources
[warn] No main class detected
ProGuard, version 5.0
ProGuard is released under the GNU General Public License. You therefore
must ensure that programs that link to it (android, ...)
carry the GNU General Public License as well. Alternatively, you can
apply for an exception with the author of ProGuard.
Reading input...
Reading program jar [/home/amit/Downloads/hello-scaloid-sbt-master/libs/weberknecht-0.1.1.jar] (filtered)
Reading program jar [/home/amit/Downloads/hello-scaloid-sbt-master/libs/autobahn-android-0.5.2-SNAPSHOT.jar] (filtered)
Reading program jar [/home/amit/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.4.jar] (filtered)
Reading program jar [/home/amit/.ivy2/cache/org.scaloid/scaloid_2.11/jars/scaloid_2.11-3.6.1-10.jar] (filtered)
Reading program jar [/home/amit/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.4.jar] (filtered)
Reading program jar [/home/amit/.ivy2/cache/org.java-websocket/Java-WebSocket/jars/Java-WebSocket-1.3.0.jar] (filtered)
Reading program jar [/home/amit/.ivy2/cache/net.sf.proguard/proguard-base/jars/proguard-base-5.1.jar] (filtered)
Reading program jar [/home/amit/Downloads/hello-scaloid-sbt-master/bin/classes.jar] (filtered)
Reading library jar [/home/amit/Android/Sdk/platforms/android-19/android.jar]
Initializing...
Note: the configuration refers to the unknown class 'scaloid.example.HelloScaloid'
Warning: de.tavendo.autobahn.Wamp: can't find referenced class org.codehaus.jackson.type.TypeReference
Warning: de.tavendo.autobahn.Wamp: can't find referenced class org.codehaus.jackson.type.TypeReference
Warning: de.tavendo.autobahn.Wamp: can't find referenced class org.codehaus.jackson.type.TypeReference
Warning: de.tavendo.autobahn.Wamp: can't find referenced class org.codehaus.jackson.type.TypeReference
Warning: de.tavendo.autobahn.WampConnection: can't find referenced class org.codehaus.jackson.type.TypeReference
Warning: de.tavendo.autobahn.WampConnection: can't find referenced class org.codehaus.jackson.type.TypeReference
Warning: de.tavendo.autobahn.WampConnection: can't find referenced class org.codehaus.jackson.type.TypeReference
Warning: de.tavendo.autobahn.WampConnection: can't find referenced class org.codehaus.jackson.type.TypeReference
Warning: de.tavendo.autobahn.WampConnection: can't find referenced class org.codehaus.jackson.type.TypeReference
Warning: de.tavendo.autobahn.WampConnection: can't find referenced class org.codehaus.jackson.type.TypeReference
Warning: de.tavendo.autobahn.WampConnection: can't find referenced class org.codehaus.jackson.type.TypeReference
Warning: de.tavendo.autobahn.WampConnection: can't find referenced class org.codehaus.jackson.type.TypeReference
Warning: de.tavendo.autobahn.WampConnection$CallMeta: can't find referenced class org.codehaus.jackson.type.TypeReference
Warning: de.tavendo.autobahn.WampConnection$CallMeta: can't find referenced class org.codehaus.jackson.type.TypeReference
Warning: de.tavendo.autobahn.WampConnection$CallMeta: can't find referenced class org.codehaus.jackson.type.TypeReference
Warning: de.tavendo.autobahn.WampConnection$CallMeta: can't find referenced class org.codehaus.jackson.type.TypeReference
Warning: de.tavendo.autobahn.WampConnection$CallMeta: can't find referenced class org.codehaus.jackson.type.TypeReference
Warning: de.tavendo.autobahn.WampConnection$CallMeta: can't find referenced class org.codehaus.jackson.type.TypeReference
Warning: de.tavendo.autobahn.WampConnection$SubMeta: can't find referenced class org.codehaus.jackson.type.TypeReference
Warning: de.tavendo.autobahn.WampConnection$SubMeta: can't find referenced class org.codehaus.jackson.type.TypeReference
Warning: de.tavendo.autobahn.WampConnection$SubMeta: can't find referenced class org.codehaus.jackson.type.TypeReference
Warning: de.tavendo.autobahn.WampConnection$SubMeta: can't find referenced class org.codehaus.jackson.type.TypeReference
Warning: de.tavendo.autobahn.WampConnection$SubMeta: can't find referenced class org.codehaus.jackson.type.TypeReference
Warning: de.tavendo.autobahn.WampConnection$SubMeta: can't find referenced class org.codehaus.jackson.type.TypeReference
Warning: de.tavendo.autobahn.WampReader: can't find referenced class org.codehaus.jackson.map.ObjectMapper
Warning: de.tavendo.autobahn.WampReader: can't find referenced class org.codehaus.jackson.map.ObjectMapper
Warning: de.tavendo.autobahn.WampReader: can't find referenced class org.codehaus.jackson.map.DeserializationConfig$Feature
Warning: de.tavendo.autobahn.WampReader: can't find referenced class org.codehaus.jackson.map.ObjectMapper
Warning: de.tavendo.autobahn.WampReader: can't find referenced class org.codehaus.jackson.map.ObjectMapper
Warning: de.tavendo.autobahn.WampReader: can't find referenced class org.codehaus.jackson.JsonFactory
Warning: de.tavendo.autobahn.WampReader: can't find referenced class org.codehaus.jackson.JsonParser
Warning: de.tavendo.autobahn.WampReader: can't find referenced class org.codehaus.jackson.JsonToken
Warning: de.tavendo.autobahn.WampReader: can't find referenced class org.codehaus.jackson.JsonToken
Warning: de.tavendo.autobahn.WampReader: can't find referenced class org.codehaus.jackson.JsonParser
Warning: de.tavendo.autobahn.WampReader: can't find referenced class org.codehaus.jackson.JsonParser
Warning: de.tavendo.autobahn.WampReader: can't find referenced class org.codehaus.jackson.JsonParser
Warning: de.tavendo.autobahn.WampReader: can't find referenced class org.codehaus.jackson.JsonParser
Warning: de.tavendo.autobahn.WampReader: can't find referenced class org.codehaus.jackson.JsonToken
Warning: de.tavendo.autobahn.WampReader: can't find referenced class org.codehaus.jackson.JsonParser
Warning: de.tavendo.autobahn.WampReader: can't find referenced class org.codehaus.jackson.JsonParseException
Warning: de.tavendo.autobahn.WampReader: can't find referenced class org.codehaus.jackson.JsonParseException
Warning: de.tavendo.autobahn.WampReader: can't find referenced class org.codehaus.jackson.JsonParser
Warning: de.tavendo.autobahn.WampReader: can't find referenced class org.codehaus.jackson.JsonParseException
Warning: de.tavendo.autobahn.WampReader: can't find referenced class org.codehaus.jackson.map.DeserializationConfig$Feature
Warning: de.tavendo.autobahn.WampReader: can't find referenced class org.codehaus.jackson.JsonFactory
Warning: de.tavendo.autobahn.WampReader: can't find referenced class org.codehaus.jackson.JsonParser
Warning: de.tavendo.autobahn.WampReader: can't find referenced class org.codehaus.jackson.JsonToken
Warning: de.tavendo.autobahn.WampReader: can't find referenced class org.codehaus.jackson.map.DeserializationConfig
Warning: de.tavendo.autobahn.WampReader: can't find referenced class org.codehaus.jackson.map.ObjectMapper
Warning: de.tavendo.autobahn.WampReader: can't find referenced class org.codehaus.jackson.JsonFactory
Warning: de.tavendo.autobahn.WampReader: can't find referenced class org.codehaus.jackson.JsonParser
Warning: de.tavendo.autobahn.WampReader: can't find referenced class org.codehaus.jackson.JsonParseException
Warning: de.tavendo.autobahn.WampWriter: can't find referenced class org.codehaus.jackson.map.MappingJsonFactory
Warning: de.tavendo.autobahn.WampWriter: can't find referenced class org.codehaus.jackson.map.MappingJsonFactory
Warning: de.tavendo.autobahn.WampWriter: can't find referenced class org.codehaus.jackson.JsonFactory
Warning: de.tavendo.autobahn.WampWriter: can't find referenced class org.codehaus.jackson.JsonGenerator
Warning: de.tavendo.autobahn.WampWriter: can't find referenced class org.codehaus.jackson.JsonGenerator
Warning: de.tavendo.autobahn.WampWriter: can't find referenced class org.codehaus.jackson.JsonGenerator
Warning: de.tavendo.autobahn.WampWriter: can't find referenced class org.codehaus.jackson.JsonGenerator
Warning: de.tavendo.autobahn.WampWriter: can't find referenced class org.codehaus.jackson.JsonGenerator
Warning: de.tavendo.autobahn.WampWriter: can't find referenced class org.codehaus.jackson.JsonGenerationException
Warning: de.tavendo.autobahn.WampWriter: can't find referenced class org.codehaus.jackson.JsonGenerationException
Warning: de.tavendo.autobahn.WampWriter: can't find referenced class org.codehaus.jackson.map.JsonMappingException
Warning: de.tavendo.autobahn.WampWriter: can't find referenced class org.codehaus.jackson.map.JsonMappingException
Warning: de.tavendo.autobahn.WampWriter: can't find referenced class org.codehaus.jackson.JsonGenerator
Warning: de.tavendo.autobahn.WampWriter: can't find referenced class org.codehaus.jackson.JsonGenerator
Warning: de.tavendo.autobahn.WampWriter: can't find referenced class org.codehaus.jackson.JsonGenerator
Warning: de.tavendo.autobahn.WampWriter: can't find referenced class org.codehaus.jackson.JsonGenerationException
Warning: de.tavendo.autobahn.WampWriter: can't find referenced class org.codehaus.jackson.map.JsonMappingException
Warning: de.tavendo.autobahn.WampWriter: can't find referenced class org.codehaus.jackson.JsonFactory
Warning: de.tavendo.autobahn.WampWriter: can't find referenced class org.codehaus.jackson.JsonGenerator
Warning: de.tavendo.autobahn.WampWriter: can't find referenced class org.codehaus.jackson.JsonFactory
Warning: de.tavendo.autobahn.WampWriter: can't find referenced class org.codehaus.jackson.JsonGenerationException
Warning: de.tavendo.autobahn.WampWriter: can't find referenced class org.codehaus.jackson.map.JsonMappingException
Warning: de.tavendo.autobahn.WampWriter: can't find referenced class org.codehaus.jackson.JsonGenerator
Note: there were 1 references to unknown classes.
      You should check your configuration for typos.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#unknownclass)
Warning: there were 75 unresolved references to classes or interfaces.
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
java.io.IOException: Please correct the above warnings first.
	at proguard.Initializer.execute(Initializer.java:473)
	at proguard.ProGuard.initialize(ProGuard.java:222)
	at proguard.ProGuard.execute(ProGuard.java:97)
	at android.Tasks$$anonfun$84.apply(tasks.scala:1260)
	at android.Tasks$$anonfun$84.apply(tasks.scala:1233)
	at scala.Function9$$anonfun$tupled$1.apply(Function9.scala:35)
	at scala.Function9$$anonfun$tupled$1.apply(Function9.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[error] (android:proguard) java.io.IOException: Please correct the above warnings first.
[error] Total time: 6 s, completed 23 Jan, 2015 11:18:16 AM

**Comment by pocorall** [comment] 2015-01-23 06:21
Looks like proguard misconfiguration for de.tavendo.autobahn. Please consider adding -dontwarn de.tavendo.autobahn.** or something.

**Comment by amitprasadom** [comment] 2015-01-23 06:46
thanks i added 
  "-dontwarn  de.tavendo.autobahn.**",
  "-dontwarn org.codehaus.jackson.**"
it worked . But my application is crashing .can i see the log on my terminal ?

**Comment by pocorall** [comment] 2015-01-23 06:50
I don't think that the problem is related with Scaloid. Post an issue when you have some specific idea about what to be improved in Scaloid.

**Comment by amitprasadom** [comment] 2015-01-23 07:07
i am not able to see log :(

**Comment by pocorall** [comment] 2015-03-09 11:17
I would close this issue, because the topic is not suitable for Scaloid issue board.

**Closed** 2015-03-09 11:17 UTC
